# Generated by Django 5.0.6 on 2024-05-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_finish_alter_trip_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
